# Generated by Django 5.1.7 on 2025-03-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ImageField(blank=True, default='article.png', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icons',
            field=models.ImageField(blank=True, default='category.png', upload_to='categoty/'),
        ),
    ]
