# Generated by Django 5.1.7 on 2025-03-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_slug_article_category_slug_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug_article',
            new_name='slug',
        ),
    ]
