# Generated by Django 5.1.7 on 2025-03-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_slug_article_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='slug_article',
        ),
    ]
